version: "3.8"

services:
    user-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: user-service
        ports:
            - "8081:8081"
        environment:
            - PORT=8081
            - MONGODB_URI=mongodb://usersrv:userpass@mongodb:27017/userdb?authSource=userdb
            - JWT_SECRET=${JWT_SECRET}
            - SERVICE_SECRET=${SERVICE_SECRET}
            - JWT_EXPIRATION=24h
        depends_on:
            mongodb:
                condition: service_healthy
        networks:
            - ecommerce-network
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:8081/health",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    mongodb:
        image: mongo:4.4
        container_name: mongodb
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin123
        volumes:
            - mongodb_data:/data/db
            - ../mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        command: --auth
        networks:
            - ecommerce-network
        healthcheck:
            test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    mongodb_data:

networks:
    ecommerce-network:
        driver: bridge
